name: tly-auto-checkin

on:
  workflow_dispatch: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  1 9 * * * 
      # 
      # https://tool.lu/crontab/
      # https://datetime360.com/cn/utc-cst-china-time/
  #watch:
  #    types: started   

jobs:
  checkin:
    runs-on: ubuntu-latest
    #if: github.event.repository.owner.id == github.event.sender.id
    # https://p3terx.com/archives/github-actions-manual-trigger.html
    
    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
      
    - name: requirements
      run: |
        pip3 install -r requirements.txt
       # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi 
    - name: Checkin
      run: |
        python3 checkin.py 
      env: 
        DOMAIN: ${{ secrets.DOMAIN }}
        USER: ${{ secrets.USER }}
        PWD: ${{ secrets.PWD }}
        KEY: ${{ secrets.KEY }}
        COOKIE: ${{ secrets.COOKIE }}
        ROBOT: ${{ secrets.ROBOT }}
        ROBOT_KEY: ${{ secrets.ROBOT_KEY }}
    - uses: gautamkrishnar/keepalive-workflow@master # using the workflow with default settings
